name: Deploy React app to Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Decide build strategy
        id: strat
        run: |
          if [ -f frontend/package.json ] && grep -q "\"build\"" frontend/package.json; then
            echo "mode=build" >> $GITHUB_OUTPUT
          elif [ -f frontend/index.html ]; then
            echo "mode=static" >> $GITHUB_OUTPUT
          else
            echo "No frontend build script and no frontend/index.html found."
            exit 1
          fi

      - name: Setup Node.js (only if build)
        if: steps.strat.outputs.mode == 'build'
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies (only if build)
        if: steps.strat.outputs.mode == 'build'
        working-directory: frontend
        run: |
          if [ -f pnpm-lock.yaml ]; then npm i -g pnpm && pnpm i || pnpm i --no-frozen-lockfile; \
          elif [ -f yarn.lock ]; then corepack enable && yarn install || yarn install --no-immutable; \
          else npm ci || npm install --legacy-peer-deps; fi

      - name: Build (only if build)
        if: steps.strat.outputs.mode == 'build'
        working-directory: frontend
        run: |
          if [ -f pnpm-lock.yaml ]; then pnpm run build; \
          elif [ -f yarn.lock ]; then yarn build; \
          else npm run build; fi

      - name: Detect artifact path
        id: detect
        run: |
          if [ "${{ steps.strat.outputs.mode }}" = "build" ]; then
            if [ -d frontend/dist ]; then echo "path=frontend/dist" >> $GITHUB_OUTPUT; exit 0; fi
            if [ -d frontend/build ]; then echo "path=frontend/build" >> $GITHUB_OUTPUT; exit 0; fi
            echo "Build finished but no dist/ or build/ folder found."; exit 1
          else
            if [ -f frontend/index.html ]; then echo "path=frontend" >> $GITHUB_OUTPUT; exit 0; fi
            echo "Static mode selected but frontend/index.html missing."; exit 1
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.detect.outputs.path }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
